repos:
  - repo: https://github.com/hmrc/security-git-hooks
    rev: release/1.15.0
    hooks:
      - id: secrets_filecontent
        name: Checking staged files for sensitive content

      - id: secrets_filename
        name: Checking staged files for sensitive file types

      - id: hooks_version_check
        name: Checking local hooks against latest release
        verbose: true
